[package]
name = "lz78-rust"
edition = "2021"
version = "0.1.0"

[dependencies]

anyhow.workspace = true
rand.workspace = true
itertools.workspace = true
serde.workspace = true
serde-pickle.workspace = true